/**
 * marketingMachine/generate.ts
 * Stub-safe generator that returns deterministic content.
 * Replace with your real generator later.
 */
import { nowIso, slugify, toTitle } from "./utils";

export type MarketingPageSpec = {
  slug: string;
  title: string;
  description: string;
  sections: Array<{ type: string; heading?: string; body?: string }>;
  generatedAt: string;
};

export function generateMarketingPageSpec(input: {
  slug?: string;
  title?: string;
  description?: string;
}): MarketingPageSpec {
  const slug = slugify(input.slug || input.title || "page");
  const title = input.title || toTitle(slug);
  const description =
    input.description ||
    "Autogenerated placeholder content (safe stub). Replace with real generator when ready.";

  return {
    slug,
    title,
    description,
    sections: [
      { type: "hero", heading: title, body: description },
      { type: "proof", heading: "Proof", body: "Before / After / Spec (stub-safe until wired)." },
      { type: "cta", heading: "Try Dominat8", body: "Generate a site, refine, SEO, publish." }
    ],
    generatedAt: nowIso()
  };
}